In [1]:
%config Completer.use_jedi = False

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [4]:
csv = pd.read_csv('/home/diemol/Insync/diemol55@gmail.com/Google Drive/Institute_of_Data/DATA/Mini Project Data/Stock_Movement.csv')

In [9]:
csv.shape

(18370, 25)

In [10]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18370 entries, 0 to 18369
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    ID            18370 non-null  int64
 1   Part           18370 non-null  object
 2   GroupCode      18370 non-null  object
 3   GroupName      18370 non-null  object
 4   Description    18206 non-null  object
 5   DocDate        18370 non-null  object
 6   Type           18370 non-null  object
 7   DocID          18370 non-null  int64
 8   Reference      18370 non-null  object
 9   Qty            18370 non-null  float64
 10  QtyFixedPrice  18370 non-null  float64
 11  Cost           18370 non-null  float64
 12  Net            18369 non-null  float64
 13  IsFixedPrice   18370 non-null  bool
 14  AccountID      16323 non-null  float64
 15  CustomerID     18370 non-null  int64
 16  CustomerName   18370 non-null  object
 17  AccountName    16321 non-null  object
 18  BranchID       18370 non-null  int64
 19  Branch         18370 non-null  object
 20  Make           0 non-null      float64
 21  Model          0 non-null      float64
 22  Registration   18370 non-null  object
 23  Plant          0 non-null      float64
 24  InvoiceType    9381 non-null   object
dtypes: bool(1), float64(8), int64(4), object(12)
memory usage: 3.4+ MB

In [11]:
csv.head()

,ID,Part,GroupCode,GroupName,Description,DocDate,Type,DocID,Reference,Qty,...,CustomerID,CustomerName,AccountName,BranchID,Branch,Make,Model,Registration,Plant,InvoiceType
0,4283,10I-SERIES,OZWIDE,OZWIDE Parts,NaN,15/09/2020 12:00:00 AM,Invoice,1498,OT45431,1.0,...,13662,Wittaya Mala,NaN,1,Ozwide Tools,NaN,NaN,QUICK SALE,NaN,Neto
1,1,AIR-R420FC,OZWIDE,OZWIDE Parts,"1/4"" Female Coupler R420FC",22/07/2020 12:00:00 AM,Invoice,185,OT43899,1.0,...,3300,Jake Stalker,HSY Canberra East (CAE),1,Ozwide Tools,NaN,NaN,QUICK SALE,NaN,Neto
2,1,AIR-R420FC,OZWIDE,OZWIDE Parts,"1/4"" Female Coupler R420FC",22/07/2020 12:00:00 AM,Invoice,210,OT43911,1.0,...,8993,David Kidd,HSY Geebung (BRN),1,Ozwide Tools,NaN,NaN,QUICK SALE,NaN,Neto
3,1,AIR-R420FC,OZWIDE,OZWIDE Parts,"1/4"" Female Coupler R420FC",22/07/2020 12:00:00 AM,Invoice,233,OT43923,1.0,...,8996,THERESA Wilson,HSY Campbellfield (MNW),1,Ozwide Tools,NaN,NaN,QUICK SALE,NaN,Neto
4,1,AIR-R420FC,OZWIDE,OZWIDE Parts,"1/4"" Female Coupler R420FC",22/07/2020 12:00:00 AM,Invoice,303,OT43966,1.0,...,8990,Joel Hili,HSY Nerang (NER),1,Ozwide Tools,NaN,NaN,QUICK SALE,NaN,Neto